[#9] Load model into ros and run inference
clockworkbits/CarND-Capstone pull request #19
Opened 2018-03-23 07:22 UTC by agotterba

Loads a model into ros, and runs inference on images received.  If an upcoming red or amber light is detected, publishes the waypoint number of that light's stopline to /traffic_waypoint.  If no light is detected, or if the light is green, publishes '-1'.  

Logs show detection/classification occurring in 2 seconds on agotterba's (rather old) desktop, but the delay from image capture to simulator reacting is ~10 seconds.  He's still working on using a cloud machine to see if performance improves.  

Here's an example of a detected red light:
![tc_image_100_red](https://user-images.githubusercontent.com/28971442/37816346-fb35820a-2e2f-11e8-8fec-e712c2380725.jpg)

amber:
![tc_image_15_amber](https://user-images.githubusercontent.com/28971442/37816385-168b5296-2e30-11e8-82e0-0c8de2bc4056.jpg)

and green:
![tc_image_93_green](https://user-images.githubusercontent.com/28971442/37816402-2814220e-2e30-11e8-9dfa-f8eb41ee4bb3.jpg)

2018-03-23 17:14 UTC, jodiealaine requested changes
Really great to see this integrated. I have just a couple of observations:

- matplotlib is not part of the ```requirements.txt``` Therefore, the following is causing the [tl_detector-8] process to die:  ```ImportError: No module named matplotlib``` on line 6 of ```tl_classifier.py``` 
  
  Luckily, we do not need this for the tl_classifier... so we can just delete that import to resolve the issue. (tested this out on my local machine and all worked well)

- We have the logic to switch between the tld_parking_lot_model and the tld_simulator_model, which is awesome. However, we appear to be missing the files (including the referenced ```frozen_inference_graph.pb```) within the ```/models/tld_parking_lot_model``` directory 

  Would it make sense to include the ```add-tld-parking-lot-model``` branch changes so we can test the logic and behaviour of the parking lot support?

2018-03-23 17:38 UTC, agotterba commented
I see- I'll remove matplot lib.  I didn't realize it wasn't in requirements.txt, and since I'm running natively my system was able to find it.  I left it in just to have in case we needed to debug false-positives.  

Including add-tld-parking-lot-model would make sense.  I'd also be excited to test that.

2018-03-24 06:30 UTC, agotterba commented
I've removed the matplotlib import, and merged the changes from add-tld-parking-lot model.  Running on the simulator or the parking lot .bag file works; there is now a constant PARKING_LOT_TEST in tl_detector.py that must be set True when running the parking lot .bag and False otherwise.  

I'm seeing a low detection rate with the parking lot .bag.  I don't think that should hold up this PR since everything is working, and low detection is still an improvement from not having the model.  I'll post details about the detection to the training issue.

2018-03-24 09:49 UTC, jodiealaine approved these changes

2018-03-24 09:49 UTC, merged